// js/MountainGame.js
// Generated by the WorldEngine

const MountainGame = {
    id: 'MountainGame',
    container: null,
    successCallback: null,
    failureCallback: null,
    sharedData: null,

    init: function(container, successCallback, failureCallback, sharedData) {
        this.container = container;
        this.successCallback = successCallback;
        this.failureCallback = failureCallback;
        this.sharedData = sharedData;

        console.log(`MountainGame: Initializing.`);
        this.render();
    },

    render: function() {
        this.container.innerHTML = `
            <div style="padding: 20px; text-align: center; color: #333; background-color: #f0f0f0; height: 100%; display: flex; flex-direction: column; justify-content: center; align-items: center; box-sizing: border-box;">
                <h1>Welcome to MountainGame</h1>
                <p>This area is under construction.</p>
                <p style="font-size: 0.8em; color: #666;">Data from Hub: ${this.escapeHtml(JSON.stringify(this.sharedData, null, 2))}</p>
                <button id="MountainGame-exit-btn" style="padding: 10px 20px; font-size: 16px; cursor: pointer; margin-top: 20px;">Exit</button>
            </div>
        `;

        document.getElementById(`MountainGame-exit-btn`).onclick = () => {
            // You can pass data back to the hub if needed, e.g., { questCompleted: 'mountain_pass' }
            this.successCallback({ message: `Returned from MountainGame` });
        };
    },
    
    escapeHtml: function(unsafe) {
        if (unsafe == null) return "";
        return String(unsafe)
             .replace(/&/g, "&amp;")
             .replace(/</g, "&lt;")
             .replace(/>/g, "&gt;")
             .replace(/"/g, "&quot;")
             .replace(/'/g, "&#039;");
    },

    destroy: function() {
        console.log(`MountainGame: Destroying.`);
        if (this.container) {
            this.container.innerHTML = '';
        }
    }
};

